### PR TITLE
bug(get-pkg) aos fails if launched on separate drive.

### LINKED ISSUE #200: aos command doesn't work globally
I installed module with this command.
```
npm i -g https://get_ao.g8way.io
```

`aos` command runs correctly on `C:\`, but has bug when I am trying to run it on `D:\` where my project is located in.

```
D:\>aos
node:fs:581
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open 'D:\Users\Admin\AppData\Roaming\npm\node_modules\@permaweb\aos\package.json'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/@permaweb/aos/src/services/get-pkg.js:12:27
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\@permaweb\\aos\\package.json'
}

Node.js v20.11.1
```

### PR DESCRIPTION
**Pull request by bliotti**
reproduced the error. I think this may fix it. 
please double check!

fixes #200

### CODE REVIEW

**Comment by bliotti** [comment]
> reproduced the error. I think this may fix it. please double check!
> 
> fixes #200

This is still broken atm, please ignore.

**Comment by bliotti** [comment]
[be4b0ff](https://github.com/permaweb/aos/pull/258/commits/be4b0ff1fc6e8399aea5cc67c88767f73a78855d) is ready to test.

**Comment by twilson63** [comment]
Thank you @bliotti I will take a look at it shortly. Also you other PR's, but TL;DR; `yarn` is the way! :)

**Comment by bliotti** [comment]
> Thank you @bliotti I will take a look at it shortly. Also you other PR's, but TL;DR; `yarn` is the way! :)
np! Enjoying the project, fun things to build and seems like things are just getting started!

**Review by twilson63 — APPROVED** [review]

**Pull request merged**
