### PR TITLE
Vince juliano/boot loader 342

### PR DESCRIPTION
**Pull request by VinceJuliano**

### CODE REVIEW

**Review by twilson63 — APPROVED** [review]
LGTM

**Comment by twilson63** [comment]
Question, why do you need a special else if for bootloader here?

https://github.com/permaweb/aos/blob/f4795225774ac988a256bff8fd8da9f11b633491/process/process.lua#L375

**Comment by VinceJuliano** [comment]
> Question, why do you need a special else if for bootloader here?
> 
> https://github.com/permaweb/aos/blob/f4795225774ac988a256bff8fd8da9f11b633491/process/process.lua#L375

So in the case of the boot loader, If there is no output from the script that gets run either via Data or via txid, we dont want the result to produce any output. If we have no extra condition here, a blank line is always printed regardless of if the boot loader script actually produced any output. So it is really just a visual bug. If the On-Boot script does produce output we see that above the prompt by the nature of AOS and the CU results endpoint.

**Comment by twilson63** [comment]
Need to think about this more, is that the case for all, if so we should
fix all if that is the desired result

**Comment by VinceJuliano** [comment]
Got it, the only way i can see to recreate the blank line on a standard Eval is to send an empty string, which then just prints a blank line, but its not really an issue here since its not visually effecting the actual boot up process - 

image

If the Boot Loader does produce output it shows above the initial prompt that appears after the eval completes, like getting a "New Message" output, this also may not be the desired behavior

**Pull request merged**
