### PR TITLE
Added Transfer-for

### PR DESCRIPTION
**Pull request by Lucifer0x17**
### There is no functionality where we can receive token on the process top do some tasks. 

- Created transfer-for Handler, which transfers the amount required and then forwards the tags to the process to complete the compute

P.S. Naming convention can be better. Please help! :)

### CODE REVIEW

**Comment by ALLiDoizCode** [comment]
This is being addressed in #212

**Comment by Lucifer0x17** [comment]
Isn't this is better as we don't have to give permission to any other address and also, we can utilise the cranking of the messages to make the whole thing more optimised.

It will be cost effective and also, as user I don't need to trust on another contract for the safety of my funds.

**Comment by ALLiDoizCode** [comment]
Yea this could work. Can you give me an example of a flow for minting and NFT or swapping a token on a DEX

**Comment by twilson63** [comment]
@Lucifer0x17 , @ALLiDoizCode , @NickJ202 , @martonlederer 

I need a little more time, but I think we can handle these use cases without having to add additional complexity to the API of the token standard.

For example, if you do a transfer, and pass any tag with a specific prefix `X-` or something, the transfer method could forward those tags via the `Credit-Notice` and `Debit-Notice`, this includes any rules required by your receiver. 

For example,

```lua
Send({Target = CRED, Action = "Transfer", Quantity = "1000", Recipient = Grid, ["X-Action"] = "Upgrade-Health", ["X-Value"] = "100" })
```

Then the token will submit the `X` tags via the `Notices` as `Tags`.

This allows you to pass any configuration rule/value you would like to via one message flow, versus having to have two flows, as well as, having to give access to your token balance. In the example of swaps, you could say.

```lua
Send({Target = CRED, Action = "Transfer", Quantity = "10000", Recipient = Grid, ["X-Action"] = "Swap", ["X-Token"] = "TRUNK", ["X-Price"] = "10", ["X-Slippage"] =  "100" })

```

This way the swap can either happen or not. What do you think?

**Comment by martonlederer** [comment]
We had a similar idea to @twilson63's proposal, but we were thinking about a few potential issues:
- Who would "pay" for the processing when the action is forwarded?
- How many "X-"s deep do we arbitrarily set to be the limit?
These are some of the questions @7i7o had, tagging him here as well.

**Comment by twilson63** [comment]
> Who would "pay" for the processing when the action is forwarded?

Still need to see the final release of payments to answer, but right now the design is that the `client` that sends the message pays for the `pushing` of any message generated as a result.

But this would be the case for any of the solutions proposed, (I think) - Even if it was the `DEX/Game` whatever that created the message, they would most likely charge the requesting client for the compute. Which may be confusing to a user using `allow/transferFrom` functionality because they will get charged for the `allow`, and the `transferFrom` and the `notices` of each. Happy to be wrong here.

**Comment by twilson63** [comment]
> How many "X-"s deep do we arbitrarily set to be the limit?

Currently, I think `Tags` have a 4096 Byte limit, I would imagine that would remain the limit. But maybe I don't understand the question.

**Comment by ALLiDoizCode** [comment]
If you checkout my pr #212 you can see my take on this which is similar but keeps the approve transferfrom flow. I replace the credit notice and all other messages actions with a generic response action and a arbitrary nonce. The idea is that if another process wants to communicate with the token it can have its own custom implementation of a response handler and the nonce that gets pasted back to it is mapped the next action

**Comment by ALLiDoizCode** [comment]
If you guys are in the discord we could hop on a voice call and discuss

**Comment by twilson63** [comment]
@ALLiDoizCode 

It would be nice to solve this without having to add complexity to the API. Any other ideas how to solve without having to add additional complexity to the API, ie change the protocol?

**Comment by ALLiDoizCode** [comment]
The complexity of the implementation doesn't effect the protocol/standard. For example

**Swap Handlers**
```
Handlers.add("response", Handlers.utils.hasMatchingTag('Action', "Response"), swap.responseHandler)
Handlers.add("transfer-error", Handlers.utils.hasMatchingTag('Action', "Transfer-Error"), swap.transferError)
Handlers.add("transferFrom-error", Handlers.utils.hasMatchingTag('Action', "TransferFrom-Error"), swap.transferFromError)
Handlers.add("errors", Handlers.utils.hasMatchingTag('Action', "Errors"), swap.errors)
```
**TransferFrom** 
This is the message the token would send back to the Swap/Client, assuming the msg contained a Nonce
```
 ao.send({
  Target = msg.Recipient,
  Action = 'Response',
  Sender = msg.OwnerId,
  Quantity = tostring(qty),
  Nonce = msg.Nonce,
})
```

**Swap**
This is a ***None Robust*** client implementation
```
function Mod.responseHandler(msg)
    if msg.Balance then
        BalanceResponse(msg)
    else
        if msg.Nonce then
            local action = Actions[msg.Nonce]
            ActionHandler(action)
        end
    end
end
```

```
function Mod.transferError(msg) 
end
```

```
function Mod.transferFromError(msg) 
end
```
So you can see that the actual footprint is small and the complexity is abstracted away to the client's implementation which in this case is the swap.

**Comment by martonlederer** [comment]
I'd support an approach where we don't need to abstract the complexity away, because there isn't any. Tom's proposal seems straight forward and would not mean many changes on either side.

**Comment by ALLiDoizCode** [comment]
@martonlederer @twilson63 IMO a token standard should only be responsible for the interface and not care about the implementation

**Comment by ALLiDoizCode** [comment]
**Prefix Pattern**

*Transfer*
Client --> Token
```lua
ao.send({
    Target = Token,
    Action = "Transfer",
    Quantity = "10000",
    Recipient = Grid,
    ["X-Action"] = "Swap",
    ["X-Token"] = "TRUNK",
    ["X-Price"] = "10",
    ["X-Slippage"] = "100"
})
```

**Response Pattern**

*Transfer*
Client --> Token
```lua
ao.send({
    OwnerId = msg.from,
    Target = Token,
    Action = "TransferFrom",
    Recipient = ao.id,
    Quantity = tostring(msg.amount),
    Nonce = msg.Nonce,
    -- Data = msg.Data,
})
```
Token --> Client
```lua
ao.send({
    Target = msg.Recipient,
    Action = 'Response',
    Sender = msg.OwnerId,
    Quantity = tostring(msg.amount),
    Nonce = msg.Nonce,
    -- Data = msg.Data,
})
```
The Nonce object Is basically just a flexible string of data, could even be a whole JSON blob if you want. By keeping it this way, the token process doesn't have to go sifting through tags to find some prefix—it's straightforward. This keeps things neat and easy, with the added perk of being able to expand using that arbitrary data. Sure, we could stick to just using the Data Tag, but in my humble opinion, we shouldn't overload the process message with stuff that's not really its business, you know? It's all about keeping things clean and focused.


The standard could even include interfaces for handling errors at the top level

**Transfer Error**
```lua
ao.send({
    Target = msg.From,
    Action = 'Transfer-Error',
    ['Message-Id'] = msg.Id,
    Error = 'Insufficient Balance!',
    Nonce = msg.Nonce,
})
```

**TransferFrom Error**
```lua
ao.send({
    Target = msg.From,
    Action = 'TransferFrom-Error',
    ['Message-Id'] = msg.Id,
    Error = 'Insufficient Balance!',
    Nonce = msg.Nonce,
})
```
```lua
ao.send({
    Target = msg.from,
    OwnerId = msg.OwnerId,
    Action = 'TransferFrom-Error',
    ['Message-Id'] = msg.Id,
    Error = 'Insufficient Allowance!',
    Nonce = msg.Nonce,
})
```

Skipping the approval step might seem like a shortcut, but it's not the best move. We're essentially putting a lot of faith in users to handle crucial data correctly when they pass it on to the token process or any other part of the system following this pattern. But let's be real here: there's a lot at stake. Whether it's the risk of someone slipping in malicious data or just a simple mistake by a user, like messing up the data before it even reaches the token, the potential for trouble is real. It's like leaving the front door unlocked—it's just asking for trouble, you know?

**Comment by ALLiDoizCode** [comment]
I had a really insightful convo with JiggyTom over on Discord, and we dug into our current `Credit Notice` flow. Here's the thing: it assumes users have to deposit their tokens into the Dapp/Dex upfront, and then the Dapp/Dex credits them using its internal system. But guess what? That's not the only way to do things.

Enter the `TransferFrom` method. This game-changer doesn't make those assumptions. It lets developers build dapps where users can keep their tokens snug in their wallets until the exact moment they need 'em for a transaction. 

Now, I know what you're thinking: "Why does this matter? Aren't users cool with trusting the process?" Well, yeah, but here's the kicker: I reached out to some dev pals, especially those in the SOL scene, where DeFi is buzzing like crazy. Asked 'em straight up: deposit or wallet? And you know what they said? Moving tokens between dapps sucks. It makes the whole ecosystem feel cramped, like you're hopping from one closed-off island to another.

But Solana? Man, that feels like a universe unto itself. All the dapps there? They feel like they're part of one big, vibrant ecosystem, seamlessly connected and flowing. That's the kind of vibe we want, right?

So yeah, this might seem like a small tweak, but trust me, it's a game-changer. It's about making our Dapp/Dex world feel bigger, more open, and more exciting for everyone involved.

**Comment by martonlederer** [comment]
Tom's implementation would also mean that no deposits are required, so I'm still not convinced.
I also don't think that just because Solana does it one way, there aren't any better options. ao is not Solana.

**Comment by ALLiDoizCode** [comment]
The TransferFor method is pretty slick and it lets developers do their thing without being tied down to a specific token flow. But it gives the first step in a flow a huge responsibility it wasn't built for. With TransferFor, we're basically asking the token process—or any process at the start of a flow—to handle a boatload of data that's way beyond its usual scope.
 
In my humble opinion, a token standard should be flexible, no doubt about it. But it should also play nice with the processes it's meant to work with. That's where the TransferFor method might be pushing it a bit too far. All that being said though I also believe its more important to get a token standard out there instead of trying to make it perfect so I would be fine with using the TransferFor Method.

Instead of using the prefix pattern why not modify the payload that the process sends in the `Credit-Notice` to use the Data field which can just be a JSON Blob or String

**Comment by martonlederer** [comment]
I'd be fine with modifying the payload. 
I disagree with the flexibility part tho. In my opinion token standards should be minimalistic for easy implementation and robust security. Everything else should be handled by the processes, depending on the token, even if that means more work. The more changes and custom functionality we allow (just for other processes' sake) the more we're risking that security.

**Comment by ALLiDoizCode** [comment]
I agree but we don't have to choose because it can be both minimalistic and flexible. This is prob out of scope for this PR but maybe we should have a discussion around the Payload schema and moving towards a general standard for this since  `Credit-Notice` is token specific and isn't really a thing for a non token process

**Comment by kprimice** [comment]
I concur that a minimalistic approach is essential, particularly in light of the security concerns associated with ERC20 and token allowances. CosmWasm provides an elegant solution by allowing the inclusion of action-specific parameters within their "Send" method, which can enhance security and functionality. This is somewhat analogous to the "X-" prefixed tags discussed here.

To improve readability and maintain the structure, I think it would be ideal to have something like the following:
```lua
Send({
    Target = CRED,
    Action = "Send",
    Quantity = "10000",
    Recipient = Pool,
    Msg = json.encode({
        Action = "Swap",
        Token = "TRUNK",
        Price = "10",
        Slippage = "100"
    })
})
```

**Comment by twilson63** [comment]
I like that approach, the only two concerns, 

1. placing JSON Strings in tags are hard to query via graphql, we have explicitly tried to avoid those conventions with ao and aos.
2. allowing a message to create another message with an Action may not be great, we have found `Credit-Notice` and `Debit-Notice` work quite well.

Curious on thoughts from others, but having inputs be first level tags have really provided nice discovery mechanisms using the arweave infrastructure. so I would lean towards prefixes versus, embedded json, but interested in other opinions.

**Comment by ALLiDoizCode** [comment]
We've gotta have messages spawning other messages, unless we're cool with sticking to that whole approve/transferFrom setup. If we don't it becomes a bit of a buzzkill for user experience, you know? Like, nobody wants to constantly shuffle tokens around just to dive into a dapp. It's like putting up barriers in our own playground. Let's keep things smooth and connected, make the whole ecosystem feel like one big happy family.

**Comment by martonlederer** [comment]
> 1. placing JSON Strings in tags are hard to query via graphql, we have explicitly tried to avoid those conventions with ao and aos.
> 
> ...
> 
so I would lean towards prefixes versus, embedded json, but interested in other opinions.
> 
> 

In that case forwarded tags make perfect sense.

**Comment by Lucifer0x17** [comment]
@twilson63 I also agree with @marton and prefer forwarded tags and But I couldn't figure it out so I took JSON approach. For now I am using that for 0rbit, till we figure out how can we forward the Tags. Also, if there will Assign function we can utilise that also here...

**Comment by twilson63** [comment]
Implemented in #221

**Pull request closed without merging**
